# Generated by Django 6.0.4 on 2026-05-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesionAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhasion_annuel_novice_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adhasion_annuel_novice_ext', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('doyen_ancien_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('doyen_ancien_ext', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.IntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('number_phone', models.CharField(max_length=20)),
                ('is_inside', models.BooleanField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('DOYEN(NE)', 'Doyen(ne)'), ('ANCIEN(NE)', 'Ancien(ne)'), ('NOVICE', 'Novice(ne)')], default='NOVICE', max_length=20)),
                ('cde', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('event_start_time', models.DateTimeField()),
                ('event_end_time', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('present_members', models.ManyToManyField(blank=True, related_name='events_attended', to='info.member')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='info.member')),
            ],
            options={
                'unique_together': {('member', 'year')},
            },
        ),
    ]
