# Generated by Django 6.0.4 on 2026-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cde',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
